### ISSUE TITLE
深入分析Java Web中280页描述的cookie被盗问题

### ISSUE THREAD

**Issue by weishengshui** [xulingbo/xulingbo.github.io#17]
《深入分析Java Web技术内幕》280页，关于cookie被盗，有一个设置session签名的解决方法。签名也是也是一个cookie，保存在浏览器客户端，同样会被盗。其他人还是可以非法登录，这样有什么用呢？

**Comment by xulingbo** [comment]
这个cookie是有时间限制的，一段时间内会自动失效的
